#!/bin/bash

ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"
valgrind --leak-check=full ../push_swap "$ARG"
ARG="$(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo) $(tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' </dev/urandom | head -c 13  ; echo)"

ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"


ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 5 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 50 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 50 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 50 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 50 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 50 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 100 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 100 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 100 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"
ARG="$(shuf -i 0-2147483647 -n 100 | awk 'BEGIN{ORS=" "}; {print}' | sed 's/ $//')"
valgrind --leak-check=full ../push_swap "$ARG" | ../checker "$ARG"

